eureka:
  client:
    serviceUrl:
      defaultZone: http://ypserver.mybluemix.net/eureka
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
    metadataMap:
      instanceId: yp_restaurant

spring:
  application:
    name: yp_restaurant
  datasource:
    url: jdbc:db2://dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
    username: lcm13498
    password: 8h638jgs7dv2^9zc
    driver-class-name: com.ibm.db2.jcc.DB2Driver

server:
  port: 8764

mybatis:
  mapper-locations: classpath:mapper.xml
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80